### ISSUE TITLE
推荐使用原版

### ISSUE THREAD

**Issue by wwwyanxin** [Corydonbyte/jiamimao#1]
https://github.com/Corydonbyte/jiamimao/

**Comment by FaiChou** [comment]
https://github.com/sh-dv/hat.sh
https://github.com/Corydonbyte/jiamimao

https://hat.sh
https://www.jiamimao.ga/

以及推广链接:
https://www.v2ex.com


请尊重原创

**Comment by yangkile** [comment]
contextMenu({
	prepend: (defaultActions, params, BrowserWindow) => [
		{
			label: 'Hat.sh :)',
			
			visible: params.mediaType === 'image'
		}
	]
});

代码里面一堆Hat.sh都还没改完你发啥...
